package com.example.msnumber.enums;

public enum ExceptionCode {
    USER_PROFILE_NOT_FOUND,
    USER_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    USER_PROFILE_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    PHONE_NUMBER_ALREADY_EXISTS,
    PHONE_NUMBER_NOT_FOUND,
}
