spring:
  application:
    name: ms-package
  datasource:
    url: jdbc:postgresql://localhost:5434/ms_package
    username: ms_package
    password: ms_package

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false


server:
  port: 8085

application:
  security:
    internal-key: mobio-local-internal-key
