spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5434/ms_auth
    username: ms_auth
    password: ms_auth

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
