spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://ms-postgres:5432/ms_auth
    username: ms_auth
    password: ms_auth

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none

application:
  security:
    internal-key: ${internal_service_key:mobio-local-internal-key}
