server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                  - X-User-Id
                  - X-User-Role
                  - X-Internal-Key
                allowCredentials: false
                maxAge: 3600

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: number-service
        url: /v3/api-docs/number-service
      - name: balance-service
        url: /v3/api-docs/balance-service
      - name: package-service
        url: /v3/api-docs/package-service
      - name: billing-service
        url: /v3/api-docs/billing-service
      - name: notification-service
        url: /v3/api-docs/notification-service
    urls-primary-name: auth-service
    display-request-duration: true
    persist-authorization: true

application:
  security:
    internal-key: mobio-local-internal-key
    jwt:
      secret-key: QmFzZTY0IGVuY29kaW5nIHNjaGVtZXMgYXJlIGNvbW1vbmx5IHVzZWQgd2hlbiB0aGVyZSBpcyBhIG5lZWQgdG8gZW5jb2RlIGJpbmFyeSBkYXRhLCBlc3BlY2lhbGx5IHdoZW4gdGhhdCBkYXRhIG5lZWRzIHRvIGJlIHN0b3JlZCBhbmQgdHJhbnNmZXJyZWQgb3ZlciBtZWRpYSB0aGF0IGFyZSBkZXNpZ25lZCB0byBkZWFsIHdpdGggdGV4dC4gVGhpcyBlbmNvZGluZyBoZWxwcyB0byBlbnN1cmUgdGhhdCB0aGUgZGF0YSByZW1haW5zIGludGFjdCB3aXRob3V0IG1vZGlmaWNhdGlvbiBkdXJpbmcgdHJhbnNwb3J0LiBCYXNlNjQgaXMgdXNlZCBjb21tb25seSBpbiBhIG51bWJlciBvZiBhcHBsaWNhdGlvbnMgaW5jbHVkaW5nIGVtYWlsIHZpYSBNSU1FLCBhcyB3ZWxsIGFzIHN0b3JpbmcgY29tcGxleCBkYXRh
      expiration: 86400000
      whitelist: /auth/**,/actuator/**,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**,/webjars/**,/api/auth/**,/api/auth-service/**,/api/auth-service/auth,/api/auth-service/auth/**,/api/auth-service/api/auth,/api/auth-service/api/auth/**
