spring:
  application:
    name: ms-balance

  datasource:
    url: jdbc:postgresql://ms-postgres:5432/ms_balance
    username: ms_balance
    password: ms_balance

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

application:
  security:
    internal-key: ${internal_service_key:mobio-local-internal-key}
