spring:
  application:
    name: ms-balance

  datasource:
    url: jdbc:postgresql://localhost:5434/ms_balance
    username: ms_balance
    password: ms_balance

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 8084

application:
  security:
    internal-key: mobio-local-internal-key
