spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://localhost:5434/ms_user
    username: ms_user
    password: ms_user

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
