server:
  port: 8083

spring:
  application:
    name: ms-number
  datasource:
    url: jdbc:postgresql://localhost:5434/ms_number
    username: ms_number
    password: ms_number

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
